[package]
name = "serialize"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
serialize_derive = { workspace = true }
openssl = { workspace = true }