[package]
name = "crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
serialize = { path = "../serialize" }
serialize_derive = { path = "../serialize_derive" }
openssl = "0.10"
rand = "0.8.5"
zeroize = "1.8.1"