[package]
name = "serialize_derive"
version = { workspace = true }
edition = "2024"  # Updated from 2021
license = { workspace = true }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }